### ISSUE TITLE
Getting unbalanced latex equations as results

### ISSUE THREAD

**Issue by GopinathCool** [lukas-blecher/LaTeX-OCR#12]
Hi, I tried with your recent commit, this time I tested with a different images but it doesn't seems to fix the issue. I am still getting unbalanced latex equation, and you also mentioned you have trained a new model, but did you uploaded it in the drive?

- I also observed that when we try to predict the same image for multiple times, it produces different latex results, is that the expected behaviour?

![patent_258_2](https://user-images.githubusercontent.com/31401733/117614174-95631f00-b185-11eb-8398-79aa26ee3fe7.png)

**Comment by lukas-blecher** [comment]
The model will always work best with the fonts specified in the [README](/lukas-blecher/LaTeX-OCR/blob/main/README.md#fonts). 
The model is able to process aliased images now. It is partly a font problem here.
Where do you find these images? Is that from mathematica? Do you know the font name?
Somewhat related: I've noticed that the model sometimes has problems with multi-line images or with repeating patterns.

As for the different predictions for the same image:
This is indeed the expected behavior. Every time the sequence is generated the next token is sampled from a probability distribution. You can adjust the distribution with the `temperature` parameter. For very small values the outcome will be the same but it does not have to be the best result. 

If the result is unbalanced try to change the temperature, or in the worst case, you have to go line by line. In your example image neither will work.
