### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by scrawfo9** [lukas-blecher/LaTeX-OCR#16]
I'm trying to install using the 
`pip install -r requirements.txt`
line of code, but it seems like my computer is stuck in an infinite loop. I successfully installed Pytorch and Python 3.7 before running the requirements line. At first it was unsuccessful and the error line recommended trying --user. No dice. I appreciate your help! I'm excited to try out your code.

**Comment by lukas-blecher** [comment]
Hi, thanks for your interest in the project!
Did the process not end after printing out 
> Successfully installed ...

If so try waiting for longer. I had the same problem before, when installing bigger packages. If it doesn't work you can still install the packages one by one.

Closing the issue because it is not directly related to the repository. If the troubles persist you can still comment below.

**Comment by scrawfo9** [comment]
I'm having trouble installing python-Levenshtein. Iran the pip install command for a week on my computer to no success. Is this the kind of thing that I can work around? Perhaps alter the code to use a different library?

**Comment by lukas-blecher** [comment]
You can check if you find your problem in the [python-Levenshtein](https://github.com/ztane/python-Levenshtein) repo.
The package is only used for calculating the edit distance during evaluation. You could just remove the part from `eval.py` or use the prior version without edit distance metric here: https://github.com/lukas-blecher/LaTeX-OCR/blob/95a9fae03fdad61cf4def5dae0fbaea86658d30d/eval.py
