### ISSUE TITLE
Latexocr box not recognised

### ISSUE THREAD

**Issue by FrankFrank9** [lukas-blecher/LaTeX-OCR#192]
When calling latexocr the box where the equation must be met it is not always recognised correctly; sometimes it does not recognise it at all. Any fixes for this? Using Mac OS for reference

**Comment by lukas-blecher** [comment]
I don't really understand what you mean. Can you give me an example snippet?

**Comment by lukas-blecher** [comment]
That is weird. 
First: If I predict from the image you sent I get `\tau_{i j}=-P\,\delta_{i j}+\mu\Big(\frac{\partial U_{i}}{\partial x_{j}}+\frac{\partial U_{j}}{\partial x_{i}}\Big),`

Are you using linux? If so, do you have gnome-screenshot installed?
If not linux, do you use macOS? Because there are issues with retina / no retina screen.

**Comment by lukas-blecher** [comment]
>  it seems like the rectangle from python GUI is not correctly captured
Yes, that can happen with the retina display (#145 for explanation)

https://github.com/lukas-blecher/LaTeX-OCR/blob/1a109bcc19e7623c436e2fabd93de98704a7ef03/pix2tex/gui.py#L276-L292

This is what I've tried to mitigate the problem. But I think it fails if you don't have a retina display and try to snip in the upper left area of the screen. No idea what to do about that.

But maybe you're right that there is another problem at hand here. How exactly did you get your prediction from the math snippet above?

**Comment by lukas-blecher** [comment]
fixed by you in #195
