### ISSUE TITLE
Whether there is a problem with vocab？

### ISSUE THREAD

**Issue by YRQ66** [lukas-blecher/LaTeX-OCR#193]
Hi! I found many unknown latex codes in the tokenizer.json, such as““ Ġ Q ": 188,"（I don't know what it means）, "" amma ": 184," Whether there is a problem in extracting word vectors. "amma" corresponds to "gamma or gamma" in the dataset. I look forward to your reply. Thank you!

**Comment by lukas-blecher** [comment]
- Ġ means " " space in HF bpe tokenization
- the "amma" is something I've noticed as well. The tokenizer is not optimized very well for the problem. But at the time I didn't know any better. It's not a problem but increases the computation needed unnecessarily. Because what most likely happens is that the model first predicts a token with "\g" and then the next token "amma". They should have been merged from the beginning.
