### ISSUE TITLE
How to run the api as a background service?

### ISSUE THREAD

**Issue by lxysl** [lukas-blecher/LaTeX-OCR#276]
Currently, run the command:
```python
python -m pix2tex.api.run
```
it will create a program in the console, and open the browser immediately.
However, I want to use the api as a background service. How can I do that?

**Comment by lukas-blecher** [comment]
There is also a background service running at port 8502.
Code at pix2tex/api/app.py
If you only want this running, try
```
uvicorn pix2tex.api.app:app --port 8502
```

**Comment by lxysl** [comment]
Thanks for the response!

**Comment by yhxiong** [comment]
![image](https://github.com/lukas-blecher/LaTeX-OCR/assets/44085182/ed8212fa-b143-4d82-9741-037d1e561be1)

It runs successfully， but the result looks like this on the website, is it the same for you?

![image](https://github.com/lukas-blecher/LaTeX-OCR/assets/44085182/a8088db6-5a7b-408c-a7f2-da9b0699fda2)

**Comment by lukas-blecher** [comment]
What you're looking at is the API and it should look like that.
Are you trying to use the WebUI? The launching is blocked by streamlit because of an user input request (they want your email, see upper part of screen shot)
You can just hit Enter to continue or in windows power shell try
```
$env:STREAMLIT_SERVER_HEADLESS = "true"
```
before starting the API.
The WebUI is located at http://localhost:8501/

**Comment by yhxiong** [comment]
Thanks for your replay.  Followed your steps and it ran successfully.

![image](https://github.com/lukas-blecher/LaTeX-OCR/assets/44085182/ee0693c2-2fc7-4630-ab6e-282739bd2d13)

But http://localhost:8502 shows the same result.

![image](https://github.com/lukas-blecher/LaTeX-OCR/assets/44085182/54feb586-8160-4f08-99f9-85f467657882)
