### ISSUE TITLE
Training?

### ISSUE THREAD

**Issue by PhenomenalOnee** [lukas-blecher/LaTeX-OCR#3]
Really Nice Work. 
Can you please provide a proper pipeline on how to train with own data.
I tried to use your formulae images and config (from google drive) to train but got error 
 RuntimeError: merge_sort: failed to synchronize: device-side assert triggered
Can you help in training.
Thanks

**Comment by lukas-blecher** [comment]
Thank you!
I will write a section in the README. Thank you for pointing it out.
I will also upload the actual settings file I used. Not sure why I didn't do it already
Did you combine the training data into a pickle file using the `dataset/dataset.py` script?
I think the problem is in the hyperparameter choice.

**Comment by lukas-blecher** [comment]
I've now written instructions and added the actual config file I used.
Please tell me if that worked for you. 
Thank you

**Comment by PhenomenalOnee** [comment]
Thanks for the quick reply,
One more help, i noticed you have used a iterable dataset
but pytorch provides IterableDataset class which offers multiprocessing and others features 
can you explain why you have not used Pytorch Dataset class.
Also num_tokens is 8000 but in tokenizer i see max vocab size is 1175 so why we need to have so much extra tokens and same 
most of seq len is below 500 (tokens/ids) so why max_seq_length is 1024
