### ISSUE TITLE
Completely unusable

### ISSUE THREAD

**Issue by itewqq** [lukas-blecher/LaTeX-OCR#33]
At first when I tried a complicated formula, it would get stuck for a long time and then returned the wrong result. 

Later, I found that even the simplest case is not recognized by this program.

![latexocr](https://user-images.githubusercontent.com/30570177/132826361-7f297b7c-7811-45a1-add8-621435629fc5.gif)

**Comment by lukas-blecher** [comment]
Hello,
I'm sorry for the difficult first contact with the program. I'll try to explain what's happening.

First regarding the complicated formula. Could you maybe show me what the input image was? Sometimes the network is suck in an feedback loop where it predicts the same token over and over again. In the end the result is most likely wrong. I will implement an early stop condition in the future. Right now I can only recommend to try again, maybe with a different temperature, or to split the image up into multiple smaller parts.

Now, regarding the simple predictions. I am aware that very small images do not work as of right now. That is due to a mistake during training where I ommited small images from the dataset. In practice that means only images with width >96px work as expected (if I recall correctly). I'm sure if you try with somewhat larger images the result will be as expected. Note, the \LaTeX command is no math typesetting and thus not in the trainingset, which is why that also didn't work.

Please let me know if you can verify what I've written down. Thanks

**Comment by itewqq** [comment]
@lukas-blecher Thanks for the reply! My issue's title may be kind of rude but it's really sad that seems everybody else can make it work except me... In fact I am very grateful for the work you've done here.

For the complicated formula, it is just the one shown in my above gif, which is a part of the README file of this repo.

For the size issue you mentioned, I just tested another bigger snip bug it still not working:
![latexocr](https://user-images.githubusercontent.com/30570177/132887779-e16d3669-76b5-4848-aba9-5204eabfc4f2.gif)

**Comment by lukas-blecher** [comment]
Thank you very much. I was able to replicate the issue. 
Turns out it was in the dependencies after all. Namely the `x-transformers`
I'll work on a fix. In the meantime you can downgrade to a previous version
```
pip install -U x-transformers==0.12.1
```
That should work.
Thanks again for brining the issue to my attention

**Comment by lukas-blecher** [comment]
I fixed the version in the requirements for now. I might come back to it at some later point but for right now that is sufficient.
