### ISSUE TITLE
[image_resizer.pth] RuntimeError: Error(s) in loading state_dict for Model

### ISSUE THREAD

**Issue by pvannyamelia** [lukas-blecher/LaTeX-OCR#58]
Hello I tried using the image_resizer.pth weight because my data often have large image size, but when I modified the pix2tex file checkpoint argument to image_resizer.pth, I got a runtime error as appeared on this screenshot I attached. Does anyone ever tried image_resizer.pth? Or any suggestions to solve this issue? 

<img width="1098" alt="Screen Shot 2021-12-06 at 15 16 43" src="https://user-images.githubusercontent.com/50089393/144811996-3ed7ea3a-43fd-4f85-bb4b-21d498556393.png">
Thank you in advance.

Here's how I modify the checkpoint argument:
<img width="891" alt="Screen Shot 2021-12-06 at 15 23 09" src="https://user-images.githubusercontent.com/50089393/144812085-d5f15eb6-00c5-4445-af06-d1576dbb7010.png">

**Comment by lukas-blecher** [comment]
Hi,
there is a misunderstanding. The image_resizer weights correspond to an entirely different network, which is also why the file sizes are significantly different.
If you place the `image_resizer.pth` file in the same directory as `weights.pth` the script will automatically initialize the classification model used for resizing. For the code see here https://github.com/lukas-blecher/LaTeX-OCR/blob/fadb0421551ff813bc5ff2b6148001b4d57c83f0/pix2tex.py#L57-L61
For very large images the resizer might still not work perfectly because I only rendered images of a set resolution range. If you find that the resizer does not help very much, consider training your own using the `train_resizer.py` script.

**Comment by pvannyamelia** [comment]
Thank you for the help

**Comment by pvannyamelia** [comment]
By the way, would you share the resolution range that the model been trained on?

**Comment by lukas-blecher** [comment]
Sure. The image sizes I trained on were at most 672x192 (wxh) and I've rendered the images randomly in between 110 and 170 dpi
Hope that answers your question.

**Comment by pvannyamelia** [comment]
thank you very much 😄
