### ISSUE TITLE
Snipping failed. (images attached)

### ISSUE THREAD

**Issue by mrd33p** [lukas-blecher/LaTeX-OCR#75]
Snipping failed for items of the third column of the following image.

![image](https://user-images.githubusercontent.com/85106864/148643503-37a3218e-7e2e-48a5-a03d-f4660b367d39.png)

same thing happened for second column of this table
![image](https://user-images.githubusercontent.com/85106864/148643540-1c54c9e8-ffb7-4385-9468-9fce7db60e8e.png)

It did not show any error but presented the wrong code like this.

![image](https://user-images.githubusercontent.com/85106864/148643556-a16c6d75-f7ce-4e8b-8cd6-986317721752.png)

Also, could you modify the app to detect equations in more than one line at one time because sometimes there is not enough space between lines, so we cannot select the area properly without including some portion of the content above or below the required equation? Also, if we try zooming on equations app almost always fails to identify the equations, whereas zooming should improve the results. Why does this happen?

**Comment by lukas-blecher** [comment]
It's all about the training domain.
The model was mostly trained with mathematical and physical equations of a certain image size range. Which is why zooming in is not helpful for the model prediction whereas zooming out could help. I've tried to solve this problem by training an image classification model to try and guess a rescaling factor such that the rescaled image resembles the training images. This does not always work, especially when the images are significantly larger.
There are no tables in the dataset and only few chemical expressions. 

To detect multi line equations is not an easy task. I think the only viable solution is to scrape much more training data from the internet, which I don't have time for right now.
