### ISSUE TITLE
video tutorial for windows installations

### ISSUE THREAD

**Issue by abirdiehard** [lukas-blecher/LaTeX-OCR#79]
Please make a video installation for using this code in windows as I am not having knowledge of python and coding..I have been using mathpix but now it's not free to use...your interface is quite similar...god bless you for making this..till the launch of  desktop version please make a video tutorial so that it would be easy for me to run python nad other things to use this code..I really need this as I have lots of pdf in which equations are there..please help...I will be grateful to you.

**Comment by lukas-blecher** [comment]
I won't make an installation video. But I can give you additional instructions:
1. Install python: https://www.python.org/downloads/
2. download this repository and extract it somewhere: https://github.com/lukas-blecher/LaTeX-OCR/archive/refs/heads/main.zip
3. Install the dependencies. For that you need to run a command shell, e.g. <kbd>WIN</kbd>+<kbd>R</kbd> and enter 'cmd', then navigate to the project dir, eg `cd C:\Users\%username%\Desktop\LaTeX-OCR-main` if the project is extracted to the Desktop
4. Run `pip install -r requirements.txt` (If that doesn't work because pip is not found, you might need to check if the python dir is added to PATH)
5. Download the model weights, as described in the README
6. run `python gui.py`

**Comment by abirdiehard** [comment]
Thanks for your reply

i will do as you suggested and god bless you for making this project and
good luck to you for a desktop version in near future.
