### ISSUE TITLE
Re: Completely unusable

### ISSUE THREAD

**Issue by jeb12301** [lukas-blecher/LaTeX-OCR#82]
Hello!

I am currently on macOS catalina 10.15.7, running python3.7. I went through the installation, and met the same problem as described in #33. I have tried all the fixes, including downgrading `x-transformers`, tuning the temperature, taking pictures of larger equations, and downloading the `weights.pth` and `image_resizer.pth` into the `checkpoints` folder, yet the program still gives out wrong results. Is there possibly some incompatibility with other distributions for my mac?

Here are my installed packages.
````
song12301(Jeb) ~ % pip3 list
Package                              Version
------------------------------------ ---------
albumentations                       1.1.0
certifi                              2021.10.8
chardet                              4.0.0
charset-normalizer                   2.0.10
click                                8.0.3
Cython                               0.29.26
einops                               0.4.0
entmax                               1.0
filelock                             3.4.2
idna                                 3.3
imageio                              2.14.0
imagesize                            1.3.0
joblib                               1.1.0
munch                                2.5.0
networkx                             2.6.3
numpy                                1.22.1
opencv-python-headless               4.5.5.62
packaging                            21.3
pandas                               1.4.0
Pillow                               9.0.0
pip                                  21.3.1
pynput                               1.7.6
pyobjc-core                          8.1
pyobjc-framework-ApplicationServices 8.1
pyobjc-framework-Cocoa               8.1
pyobjc-framework-Quartz              8.1
pyparsing                            3.0.7
PyQt5                                5.15.6
PyQt5-Qt5                            5.15.2
PyQt5-sip                            12.9.0
PyQtWebEngine                        5.15.5
PyQtWebEngine-Qt5                    5.15.2
python-dateutil                      2.8.2
python-Levenshtein                   0.12.2
pytz                                 2021.3
PyWavelets                           1.2.0
PyYAML                               6.0
qudida                               0.0.4
regex                                2022.1.18
requests                             2.27.1
sacremoses                           0.0.47
scikit-image                         0.19.1
scikit-learn                         1.0.2
scipy                                1.7.3
screeninfo                           0.8
setuptools                           60.5.0
six                                  1.16.0
threadpoolctl                        3.0.0
tifffile                             2021.11.2
timm                                 0.5.4
tokenizers                           0.9.4
torch                                1.10.1
torchtext                            0.11.1
torchvision                          0.11.2
tqdm                                 4.62.3
typing_extensions                    4.0.1
urllib3                              1.26.8
wheel                                0.37.1
wincertstore                         0.2
x-transformers                       0.12.1
````

Thanks a lot for your time!

**Comment by lukas-blecher** [comment]
Can you give me an example image? Maybe it's the resizer not working properly. Can you try again with a smaller resolution of the equations?

**Comment by jeb12301** [comment]
Thanks for the quick reply. Here is an screenshot of me attempting to do the ocr on the d\ell = \sum\limit_{i=1}^{3} ... part
<img width="1213" alt="Screenshot 2022-01-23 at 8 04 15 PM" src="https://user-images.githubusercontent.com/98257374/150677580-d3b5991d-64f3-4a8d-9ed4-d886fa957022.png">

**Comment by lukas-blecher** [comment]
Copy the image below into your clipboard by right click -> copy image.
![image](https://user-images.githubusercontent.com/55287601/150677916-b1c64bd2-11a1-42e6-9b7c-eeea444aaa35.png)
Then run `python pix2tex.py` and hit enter as soon as it's ready.
On my machine the following is the output:
```
\mathrm{d}\ell=\sum_{i=1}^{3}h_{i}\ \mathrm{d}u_{i}\hat{u}_{i}=h_{1}\ \mathrm{d}u_{1}\hat{u}_{1}+h_{2}\ \mathrm{d}u_{2}\hat{u}_{2}+h_{3}\ \mathrm{d}u_{3}\hat{u}_{3}
```
What do you get?

**Comment by jeb12301** [comment]
I get '\mathrm{d}\ell=\sum_{i=1}^{3}h_{i}\ \mathrm{d}u_{i}\hat{u}_{i}=h_{1}\ \mathrm{d}u_{1}\hat{u}_{1}+h_{2}\ \mathrm{d}u_{2}\hat{u}_{2}+h_{3}\ \mathrm{d}u_{3}\hat{u}_{3}'

**Comment by lukas-blecher** [comment]
Ok so there is no problem with the dependencies. It most likely is the image resizer. I'll try to fix that in the future.
For now make sure your snips are of lower resolution.

**Comment by lukas-blecher** [comment]
I found a bug. Not sure if it is related to this problem but I recommend you pull the changes :)

**Comment by jeb12301** [comment]
Hmm the gui version still does not work

**Comment by lukas-blecher** [comment]
Are you using multiple monitors?
Does the following snippet create a correct screen shot?
```python
from PIL import ImageGrab
im=ImageGrab.grab(all_screens=True)
im.show()
```

**Comment by jeb12301** [comment]
Nope, using mac laptop. The snippet provides the correct screenshot.

**Comment by rainyl** [comment]
I met the same problem recently, the problem seems to be related to the resolution(or Image.size probably?) of the image.

Failed image sample(from this repo's README):
![snip](https://user-images.githubusercontent.com/30213663/157356312-0b4ae7d4-916e-4757-b5e7-5d2ca208b8fb.png)

Result: \left.{\bar{\theta}}_{\rightarrow}\right|_{\left\langle\left|\phi\right|}^{\left|}\right\rangle_{\left|\phi\right\rangle}^{\left|\left\langle\left|\phi\right|}\right|_{\left|\phi\right|}^{\left|}\right\rangle_{\left|\phi\right|}\left|\psi\right\rangle_{\right|}\right\rangle_{\left|\left\langle\left|\right\rangle\right|}


![image](https://user-images.githubusercontent.com/30213663/157356977-b5260b77-f544-4124-b852-09fe7caa19f8.png)


BUT, if I zoom the image into 200% or 50%, and take a screenshot, it will be success.

then, i saved the image processed in `call_model` before im=t.to(device), is shows:
![call_model_resized](https://user-images.githubusercontent.com/30213663/157357698-ef624e0c-cc9a-4595-b39b-04dfb4abfdae.png)

but for correct predict, it was:
![call_model_resized](https://user-images.githubusercontent.com/30213663/157357788-10c548a6-340b-4978-8c97-8049347759b2.png)

for now , i still don't know how to solve the problem, so, i am here to ask for help, thanks a lot!

**Comment by rainyl** [comment]
Finally, i managed to solve the problem, since the  failing reason was that the image was resized to improper ratio, so i modified the code about resize in `call_model` to the following:

![image](https://user-images.githubusercontent.com/30213663/157360568-58a1f985-b0a4-4947-99f3-6e98e00fe187.png)

For now, it works properly.
